# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: silly.proto for package ''

require 'grpc'
require 'silly_pb'

module Silly
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Silly'

    rpc :SleepFor, ::SleepRequest, ::SleepResponse
  end

  Stub = Service.rpc_stub_class
end
