# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: silly.proto

require 'google/protobuf'


descriptor_data = "\n\x0bsilly.proto\" \n\x0cSleepRequest\x12\x10\n\x08\x64uration\x18\x01 \x02(\x05\" \n\rSleepResponse\x12\x0f\n\x07message\x18\x01 \x02(\t22\n\x05Silly\x12)\n\x08SleepFor\x12\r.SleepRequest\x1a\x0e.SleepResponse"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

SleepRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SleepRequest").msgclass
SleepResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SleepResponse").msgclass
